Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -86,10 +86,11 @@ jobs:
           chmod 777 ${{ github.workspace }}/report
           while IFS= read -r endpoint; do
             echo "Scanning endpoint: $endpoint"
-            docker run -v ${{ github.workspace }}/report:/zap/wrk:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t "https://dummy-backend-check.onrender.com$endpoint" -r /zap/wrk/$(basename $endpoint).html
+            docker run -v ${{ github.workspace }}/report:/zap/wrk:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t "https://dummy-backend-check.onrender.com$endpoint" -r /zap/wrk/$(basename $endpoint).html || true
           done < endpoints.txt
 
       - name: Upload ZAP Reports
+        if: always()  # Ensure this step runs regardless of previous failures
         uses: actions/upload-artifact@v2
         with:
           name: zap-reports
